<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

// Used as API 
class Comm extends CI_Controller {

	// Converts pnml to c
	public function convert() {	
		$pnml = $_POST['pnml'];
		$app_root = realpath(BASEPATH . "/../");
		// $fileName = $app_root . "/tmp/test";// . (md5(microtime() + rand()));
		$fileName = $app_root . "/tmp/" . "Petrolino";//(md5(microtime() + rand()));
		$fh = fopen($fileName . ".pnml", 'w+') or die("can't open file" . $fileName);
		fwrite($fh, $pnml);
		fclose($fh);
		
		echo shell_exec("python " . $app_root . "/assets/petripy/petripy.py " . $fileName . ' 2>&1');	
	}
	
	// Creates pnml file on server
	public function createPNML() {
		
		// Get pnml data
		$pnml = $_POST['pnml'];
		
		// Write to file
		$app_root = realpath(BASEPATH . "/../");
		$fileName = $app_root . "/tmp/" . (md5(microtime() + rand()));
		$fh = fopen($fileName . ".pnml", 'w+') or die("can't open file" . $fileName);
		
		fwrite($fh,"<!-- This file has been generated by Petrolino. -->\n");
		fwrite($fh, $pnml);
		fclose($fh);
		
		// Save filename in session
		$this->load->library('session');
		$this->session->set_flashdata('filename', ($fileName));
		echo true;
	}
	
	// Downloads pnml file from server
	public function downloadPNML() {
	$this->load->helper('download');
	$this->load->library('session');
	
	$data = file_get_contents($this->session->flashdata('filename').".pnml");
	$name = 'Petrolino.pnml';

	force_download($name, $data);
	}
	
}

?>
